### ISSUE TITLE
Cannot figure out why Jabber alerts are not working.

### ISSUE THREAD

**Issue by ianc125** [kanboard/plugin-jabber#5]

**Comment by tomamplius** [comment]
Same issue for me

**Comment by tjharman** [comment]
Did anyone get to the bottom of this?

**Comment by ianc125** [comment]
I never did

**Comment by fernandogiacomino** [comment]
Hi @ianc125! I have the same problem with an openfire server, when the shipping address set in Kanboard belongs to the same domain as the destination address. I did tests to send with an external server and it worked without problems. Then I did tests with Prosody running on Raspberry Pi with the basic configuration and it also works! I'm receiving on Openfire accounts but can´t send with. I still can not identify in the Openfire log what the problem is.

**Comment by yvangodard** [comment]
Exactly the same problem here with shipping address set in Kanboard belonging to the same domain as the destination address. Any solution ?

**Comment by Thraze** [comment]
Hi all, I had the exact same issue. For me it was the ejabberd certificate. Ejabberd normally uses one pem file with the key and certificate in it. I had to add all intermediate certificates.

I did it with let's encrypt and put the contents of privkey.pem and fullchain.pem in one file which is used by ejabberd.

In my kanboard I only enabled the jabber notifications, added my xmpp-account in my profile and set the systems xmpp-account just like you did. 

Hope this helps!

**Comment by jhererxp** [comment]
Hi! Would like to first thank @fguillot for creating one of the awesomest opensource ever. I consider myself a noob when it comes to connecting with XMPP. I have an Openfire server running with multiple Spark clients that work well. Also have the Conversations (android app) working with the Openfire server. However I'm stuck connecting Kanboard with our Openfire server even if I followed the instructions and triple-checked the procedures. Anything I'm missing?

It seems like it's related with an SSL error based from the debug log. This is a sample debug log output when I create a new task:

> 2020.01.27 22:18:42 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event SESSION_OPENED to session 2034
Queue : [SESSION_OPENED, ]

2020.01.27 22:18:42 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event MESSAGE_RECEIVED to session 2034
Queue : [SESSION_OPENED, , MESSAGE_RECEIVED, ]

2020.01.27 22:18:42 org.apache.mina.filter.codec.ProtocolCodecFilter - Processing a MESSAGE_RECEIVED for session 2034
2020.01.27 22:18:42 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event MESSAGE_SENT to session 2034
Queue : [MESSAGE_SENT, ]

2020.01.27 22:18:42 org.jivesoftware.openfire.net.SASLAuthentication - Cannot support 'GSSAPI' as the 'sasl.gssapi.config' property has not been defined.
2020.01.27 22:18:42 org.jivesoftware.openfire.net.SASLAuthentication - Cannot support 'JIVE-SHAREDSECRET' as it has been disabled by configuration.
2020.01.27 22:18:42 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event MESSAGE_SENT to session 2034
Queue : [MESSAGE_SENT, , MESSAGE_SENT, ]

2020.01.27 22:18:42 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event MESSAGE_RECEIVED to session 2034
Queue : [MESSAGE_RECEIVED, ]

2020.01.27 22:18:42 org.apache.mina.filter.codec.ProtocolCodecFilter - Processing a MESSAGE_RECEIVED for session 2034
2020.01.27 22:18:42 org.jivesoftware.openfire.keystore.OpenfireX509TrustManager - Constructed trust manager. Number of trusted issuers: 0, accepts self-signed: true, checks validity: true
2020.01.27 22:18:42 org.jivesoftware.openfire.keystore.OpenfireX509TrustManager - Constructed trust manager. Number of trusted issuers: 0, accepts self-signed: true, checks validity: true
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslFilter - Adding the SSL Filter tls to the chain
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Session Server[2034](no sslEngine) Initializing the SSL Handler
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Session Server[2034](no sslEngine) SSL Handler Initialization done.
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslFilter - Session Server[2034](ssl...) : Starting the first handshake
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Session Server[2034](ssl...) processing the NEED_UNWRAP state
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslFilter - Session Server[2034](ssl...): Writing Message : WriteRequest: HeapBuffer[pos=0 lim=50 cap=64: 3C 70 72 6F 63 65 65 64 20 78 6D 6C 6E 73 3D 22...]
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslFilter - Session Server[2034](ssl...): Message received : HeapBuffer[pos=0 lim=517 cap=1024: 16 03 01 02 00 01 00 01 FC 03 03 F0 61 CC 21 EB...]
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Session Server[2034](ssl...) Processing the received message
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Session Server[2034](ssl...) processing the NEED_UNWRAP state
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Session Server[2034](ssl...) processing the NEED_TASK state
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Session Server[2034](ssl...) processing the NEED_WRAP state
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslFilter - Session Server[2034](ssl...): Writing Message : WriteRequest: HeapBuffer[pos=0 lim=1210 cap=2115: 16 03 03 04 B5 02 00 00 51 03 03 5E 2E F1 42 FD...]
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Session Server[2034](ssl...) processing the NEED_UNWRAP state
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslFilter - Session Server[2034](ssl...): Processing the SSL Data
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslFilter - Session Server[2034](ssl...): Message received : HeapBuffer[pos=0 lim=7 cap=1024: 15 03 03 00 02 02 2E]
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Session Server[2034](ssl...) Processing the received message
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Session Server[2034](ssl...) processing the NEED_UNWRAP state
2020.01.27 22:18:42 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event EXCEPTION_CAUGHT to session 2034
Queue : [EXCEPTION_CAUGHT, ]

2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslFilter - Session Server[2034](ssl...): Writing Message : WriteRequest: HeapBuffer[pos=0 lim=145 cap=256: 3C 73 74 72 65 61 6D 3A 65 72 72 6F 72 20 78 6D...]
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslFilter - Session Server[2034](ssl...): Writing Message : WriteRequest: HeapBuffer[pos=0 lim=16 cap=16: 3C 2F 73 74 72 65 61 6D 3A 73 74 72 65 61 6D 3E]
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslFilter - Session Server[2034]: Writing Message : WriteRequest: HeapBuffer[pos=0 lim=7 cap=8: 15 03 03 00 02 01 00]
2020.01.27 22:18:42 org.apache.mina.filter.ssl.SslHandler - Unexpected exception from SSLEngine.closeInbound().
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
at sun.security.ssl.Alerts.getSSLException(Unknown Source)
at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source)
at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source)
at sun.security.ssl.SSLEngineImpl.closeInbound(Unknown Source)
at org.apache.mina.filter.ssl.SslHandler.destroy(SslHandler.java:204)
at org.apache.mina.filter.ssl.SslFilter.sessionClosed(SslFilter.java:439)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:382)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$900(DefaultIoFilterChain.java:47)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.sessionClosed(DefaultIoFilterChain.java:750)
at org.apache.mina.core.filterchain.IoFilterAdapter.sessionClosed(IoFilterAdapter.java:88)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextSessionClosed(DefaultIoFilterChain.java:382)
at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireSessionClosed(DefaultIoFilterChain.java:375)
at org.apache.mina.core.service.IoServiceListenerSupport.fireSessionDestroyed(IoServiceListenerSupport.java:244)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.removeNow(AbstractPollingIoProcessor.java:600)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.removeSessions(AbstractPollingIoProcessor.java:560)
at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$800(AbstractPollingIoProcessor.java:67)
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1132)
at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
2020.01.27 22:18:42 org.apache.mina.filter.executor.OrderedThreadPoolExecutor - Adding event SESSION_CLOSED to session 2034
Queue : [SESSION_CLOSED, ]

2020.01.27 22:18:42 org.jivesoftware.openfire.spi.RoutingTableImpl - Removing client route vm-t/2o1iodm2r7


Any help would be much appreciated! I'm more than desperate to make this work for our project! I'm also willing to tip you a drink!

**Comment by fernandogiacomino** [comment]
@jhererxp I recommend you explore this: [https://github.com/fabiang/xmpp/issues](https://github.com/fabiang/xmpp/issues) and also try the latest version of the base library: [https://packagist.org/packages/norgul/xmpp-php](https://packagist.org/packages/norgul/xmpp-php).
Some time ago I got it to work following some suggested correction in the issues, then I lost it. The problem seems to be on the side of self-signed certificates.
